### ISSUE TITLE
Link for implmentation

### ISSUE THREAD

**Issue by fahad-mukhtar** [romychab/Slide-to-unlock#1]
can you please share the implementation link for this library?

**Comment by romychab** [comment]
@fahad-mukhtar This library is not published to any public maven repository and also it is not supported for ages. If you still want to use it you can add 'slidetounlock' module to your project manually: 
1) Copy 'slidetounlock' directory from the repository into your root project directory.
2) Register module in the settings.gradle: `include ':slidetounlock'`
3) Add dependency to the build.gradle: `implementation project(':slidetounlock')''
